name: Android CI (Build APK)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"
          components: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Create local.properties with SDK path
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Install Gradle 8.7 (no wrapper)
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle -v

      - name: Build Debug APK
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: VolumeLock-debug-apk
          path: app/build/outputs/apk/debug/*.apk
